[package]
name = "file-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
crossterm = { version = "0.28.1", features = ["event-stream"] }
futures = "0.3.31"
open = "5.3.2"
ratatui = "0.29.0"
tokio = { version = "1.40.0", features = ["full"] }
trash = "5.2.1"
